# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simple-iOS
  pod 'Kingfisher', '~> 7.0'

  target 'simple-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
